# Generated by Django 2.2.4 on 2020-03-20 10:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0002_auto_20200317_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partido', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'partido',
                'verbose_name_plural': 'partidos',
            },
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
            },
        ),
        migrations.CreateModel(
            name='CCZE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100, null=True)),
                ('comando', models.CharField(max_length=100, null=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326)),
                ('respTerrPartido', models.ForeignKey(on_delete=False, to='emergencias.partido')),
                ('respTerrProvincia', models.ManyToManyField(to='emergencias.provincia')),
            ],
            options={
                'verbose_name': 'CCZE',
                'verbose_name_plural': 'CCZEs',
            },
        ),
    ]
