# Generated by Django 2.2.4 on 2020-03-09 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='termino',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
