# Generated by Django 2.2.4 on 2020-03-09 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meys', '0002_documento_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='img',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='destino',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
