# Generated by Django 2.2.4 on 2020-03-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meys', '0003_auto_20200309_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='destino',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.CharField(max_length=100),
        ),
    ]
