# Generated by Django 2.2.4 on 2020-03-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meys', '0004_auto_20200309_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='img',
        ),
    ]
