# Generated by Django 2.2.4 on 2020-03-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meys', '0005_remove_documento_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='termino',
            field=models.DateTimeField(verbose_name='termino'),
        ),
    ]
