# Generated by Django 2.2.4 on 2020-03-10 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meys', '0006_auto_20200309_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='archivos/'),
            preserve_default=False,
        ),
    ]
